shell = "zsh"

[plugins]

# 遅延読み込み
[plugins.zsh-defer]
  github = "romkatv/zsh-defer"

# 履歴補完
[plugins.zsh-autosuggestions]
  apply  = ["defer"]
  github = "zsh-users/zsh-autosuggestions"

# 補完
[plugins.zsh-completions]
  apply  = ["defer"]
  github = "zsh-users/zsh-completions"

# ハイライト
[plugins.zsh-syntax-highlighting]
  github = "zsh-users/zsh-syntax-highlighting"

# 構文ハイライト
[plugins.fast-syntax-highlighting]
  github = "zdharma/fast-syntax-highlighting"

[templates]
  defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
