#!/usr/bin/env sh

# global settings
yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config                                 \
    top_padding                  06             \
    bottom_padding               10             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   04

yabai -m config window_opacity on

# Rules
yabai -m rule --add                             \
    app="^System Preferences$" manage=off       \
    app="^Electron$"           manage=off       \

echo "yabai configuration loaded..."
