[window]
  decorations = "transparent"
  opacity     = 0.75
  padding     = { x = 12, y = 24 }
  title       = "Terminal"

[scrolling]

[font]
  bold        = { family = "JetBrainsMono Nerd Font", style = "Bold" }
  bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
  italic      = { family = "JetBrainsMono Nerd Font", style = "Italic" }
  normal      = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  offset      = { x = 1, y = 1 }
  size        = 13

[colors]

[colors.primary]
  background = "#FFFFFF"
  foreground = "#1E355B"

[colors.normal]
  black   = "#333642"
  blue    = "#AC7AE8"
  cyan    = "#7AB8CC"
  green   = "#3AF14D"
  magenta = "#E859A4"
  red     = "#AC7AE8"
  white   = "#C9C9B8"
  yellow  = "#C6C641"

[colors.bright]
  black   = "#333642"
  blue    = "#AC7AE8"
  cyan    = "#7AB8CC"
  green   = "#3AF14D"
  magenta = "#E859A4"
  red     = "#AC7AE8"
  white   = "#C9C9B8"
  yellow  = "#C6C641"

[colors.dim]
  black   = "#333642"
  blue    = "#AC7AE8"
  cyan    = "#7AB8CC"
  green   = "#3AF14D"
  magenta = "#E859A4"
  red     = "#AC7AE8"
  white   = "#C9C9B8"
  yellow  = "#C6C641"

[bell]

[selection]

[cursor]
  style = { shape = "Beam", blinking = "On" }

[terminal]

[mouse]
  bindings         = [{ mouse = "Right", mods = "Control", action = "Paste" }]
  hide_when_typing = true

[hints]

[keyboard]
